apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      containers:
        - name: expressjs
          image: cookieboiz/expressjs-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: expressjs-service
spec:
  selector:
    app: expressjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
